=== crinuyi/XML-projects/schema/project.xsd
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:element name="project" type="typProjekt"/>
    <xsd:complexType name="typProjekt">
        <xsd:sequence>
            <xsd:element name="strona" type="typStrona"/>
        </xsd:sequence>
    </xsd:complexType>



<!--_________________________________________________________-->
      <xsd:complexType name="typStrona">
        <xsd:sequence>
            <xsd:element name="rysunki" type="typRysunki"/>
            <xsd:element name="forum" type="typForum"/>
              <xsd:element name="sklep" type="typSklep"/>
      </xsd:sequence>
      </xsd:complexType>



<!--_________________________________________________________-->
    <xsd:complexType name="typRysunki">
        <xsd:sequence>
            <xsd:element name="kategoria" type="typKategoria" maxOccurs="unbounded"/>
         </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="typKategoria">
        <xsd:sequence>
               <xsd:element name="podkategoria" type="typPodkategoria"/>
        </xsd:sequence>
            <xsd:attribute name="nazwa_rysunek" type="xsd:string"/>
    </xsd:complexType>
    <xsd:complexType name="typPodkategoria">
        <xsd:sequence>
            <xsd:element name="nazwa" type="xsd:string"/>
            <xsd:element name="autor" type="xsd:string"/>
            <xsd:element name="rozmiar" type="xsd:float"/>
            <xsd:element name="opis" type="xsd:string"/>
            <xsd:element name="dlugosc" type="xsd:integer"/>
            <xsd:element name="szerokosc" type="xsd:integer"/>
        </xsd:sequence>
        <xsd:attribute name="nazwa_rysunek" type="xsd:string"/>
        <xsd:attribute name="id" type="xsd:integer"/>
    </xsd:complexType>

<!--_________________________________________________________-->
    <xsd:complexType name="typForum">
        <xsd:sequence>
            <xsd:element name="dzial" type="typDzial" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>
        <xsd:complexType name="typDzial">
        <xsd:sequence>
            <xsd:element name="temat" type="typTemat" maxOccurs="unbounded"/>
        </xsd:sequence>
            <xsd:attribute name="nazwa_dzial" type="xsd:string"/>
    </xsd:complexType>
    <xsd:complexType name="typTemat">
        <xsd:sequence>
            <xsd:element name="nazwa" type="xsd:string"/>
            <xsd:element name="odpowiedzi" type="xsd:integer"/>
            <xsd:element name="wyswietlenia" type="xsd:integer"/>
        </xsd:sequence>
        <xsd:attribute name="zatwierdzony" type="xsd:string"/>
    </xsd:complexType>



<!--_________________________________________________________-->
    <xsd:complexType name="typSklep">
        <xsd:sequence>
            <xsd:element name="kategoria_sklep" type="typKategoriaSklep" minOccurs="2" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="typKategoriaSklep">
        <xsd:sequence>
            <xsd:element name="autor" type="xsd:string"/>
            <xsd:element name="seria" type="xsd:string"/>
            <xsd:element name="cena" type="xsd:positiveInteger"/>
            <xsd:element name="cena_wysylki" type="xsd:unsignedInt"/>
            <xsd:element name="czas_oczekiwania" type="xsd:string"/>
        </xsd:sequence>
        <xsd:attribute name="nazwa_sklep" type="xsd:string"/>
    </xsd:complexType>

</xsd:schema>

=== crinuyi/XML-projects/schema/project.xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="project.xsd">
<strona>
    <rysunki>
        <kategoria nazwa_rysunek="rysunek cyfrowy">
            <podkategoria nazwa_rysunek="krajobraz" id="001">
                <nazwa>rysunek1</nazwa>
                <autor>nick1</autor>
                <rozmiar>2</rozmiar>
                <opis>opis1</opis>
                <dlugosc>2000</dlugosc>
                <szerokosc>1000</szerokosc>
            </podkategoria>
        </kategoria>
        <kategoria nazwa_rysunek="rysunek tradycyjny">
            <podkategoria nazwa_rysunek="fanart" id="002">
                <nazwa>rysunek2</nazwa>
                <autor>nick2</autor>
                <rozmiar>1.45</rozmiar>
                <opis>opis2</opis>
                <dlugosc>1500</dlugosc>
                <szerokosc>699</szerokosc>
            </podkategoria>
        </kategoria>
        <kategoria nazwa_rysunek="rysunek tradycyjny">
            <podkategoria nazwa_rysunek="fanart" id="003">
                <nazwa>rysunek3</nazwa>
                <autor>nick3</autor>
                <rozmiar>0.67</rozmiar>
                <opis>opis3</opis>
                <dlugosc>200</dlugosc>
                <szerokosc>125</szerokosc>
            </podkategoria>
        </kategoria>
        <kategoria nazwa_rysunek="rysunek cyfrowy">
            <podkategoria nazwa_rysunek="fanart" id="004">
                <nazwa>rysunek4</nazwa>
                <autor>nick4</autor>
                <rozmiar>22</rozmiar>
                <opis>opis4</opis>
                <dlugosc>6943</dlugosc>
                <szerokosc>5046</szerokosc>
            </podkategoria>
        </kategoria>
        <kategoria nazwa_rysunek="rysunek cyfrowy">
            <podkategoria nazwa_rysunek="postać własna" id="005">
                <nazwa>rysunek5</nazwa>
                <autor>nick5</autor>
                <rozmiar>6</rozmiar>
                <opis>opis4</opis>
                <dlugosc>2646</dlugosc>
                <szerokosc>1254</szerokosc>
            </podkategoria>
        </kategoria>
    </rysunki>
    <forum>
            <dzial nazwa_dzial="zakupy">
                    <temat zatwierdzony="tak">
                        <nazwa>Ile kosztują promarkery?</nazwa>
                        <odpowiedzi>45</odpowiedzi>
                        <wyswietlenia>4578</wyswietlenia>
                    </temat>
                    <temat zatwierdzony="tak">
                        <nazwa>Najtańszy kurs malarstwa (książka)</nazwa>
                        <odpowiedzi>3</odpowiedzi>
                        <wyswietlenia>654</wyswietlenia>
                    </temat>
            </dzial>
            <dzial nazwa_dzial="porady">
                <temat zatwierdzony="tak">
                    <nazwa>Jak nauczyć się anatomii?</nazwa>
                    <odpowiedzi>656</odpowiedzi>
                    <wyswietlenia>10765</wyswietlenia>
                </temat>
            </dzial>
    </forum>
    <sklep>
        <kategoria_sklep nazwa_sklep="koszulka">
            <autor>autor1</autor>
            <seria>seria1</seria>
            <cena>56</cena>
            <cena_wysylki>12</cena_wysylki>
            <czas_oczekiwania>15 dni</czas_oczekiwania>
        </kategoria_sklep>
        <kategoria_sklep nazwa_sklep="koszulka">
            <autor>autor1</autor>
            <seria>seria2</seria>
            <cena>40</cena>
            <cena_wysylki>12</cena_wysylki>
            <czas_oczekiwania>15 dni</czas_oczekiwania>
        </kategoria_sklep>
        <kategoria_sklep nazwa_sklep="kubek">
            <autor>autor2</autor>
            <seria>seria1</seria>
            <cena>20</cena>
            <cena_wysylki>6</cena_wysylki>
            <czas_oczekiwania>15 dni</czas_oczekiwania>
        </kategoria_sklep>
        <kategoria_sklep nazwa_sklep="plakat">
            <autor>autor3</autor>
            <seria>seria3</seria>
            <cena>7</cena>
            <cena_wysylki>2</cena_wysylki>
            <czas_oczekiwania>15 dni</czas_oczekiwania>
        </kategoria_sklep>
    </sklep>
</strona>
</project>
